### PR TITLE
Tidy - closes #33

### LINKED ISSUE #33: Tidy up folder
There are files all over the place!

- Suggest placing all the Python files in a `src/osemosys_global` folder
- Delete all the `.ipynb` files if they duplicate what is in the script.  
- Alternatively, if the `.ipynb` files are to be retained (e.g. as a user-friendly option), suggest importing the new Python scripts, deleting the contained code (perhaps you've done this already, and moving all notebooks to a `notebooks` folder

### PR DESCRIPTION
**Pull request by willu47**
- Moves new Python files to `src/osemosys_global` (standard location for a Python package)
- Move all Jupyter notebooks to `notebooks` folder
- Remove unwanted output data
- Ignore csv and text files in the repo

### CODE REVIEW

**Comment by tniet** [comment]
Hi @willu47 - thanks for the cleanup work!  One question:  You note "Ignore csv and text files in the repo".  A bunch of the input data that is in the data directory is csv files, and the package isn't very useful without that.  Before accepting this pull I want to check that this won't break the repo.

**Comment by willu47** [comment]
Sorry, my comment was wasn't very clear. I added `*.csv` and `*.txt` to the `.gitignore` file. This will prevent new files of those types being accidentally tracked and committed. Existing files that are already tracked, such as the contents of the `data` folder will be unaffected.

You can also override the ignore using `git add -f my file.txt`

**Comment by willu47** [comment]
@tniet I also notice many of the Jupyter notebooks are still present even though your pull request deleted them? Should they be removed?

**Comment by tniet** [comment]
I was ready to delete them (they will eventually all be removed) but @abhishek0208 suggested we wait a few days before doing so.  They should be deleted once we’ve confirmed we haven’t missed anything in the scripts.

**Pull request merged**
