### PR TITLE
Updates dependencies 

### LINKED ISSUE #212: [FEATURE]: Update dependency versions
### Idea

With python 3.13 now released, we should really do a general dependency update. These are the big ones I see that should be addressed: 
- `otoole>=1.1.3` -> Required for corrected capital investment accounting
- `pandas>= 2.2` -> A breaking change in otoole caused the previous requirement of `pandas<=2.0.2`. This can be relaxed now
- `snakemake>=8.0` -> Version 8 was quite a big update and has been out for ~ 1y year now. This drop install for `snakemake-minimal`
- `python>=3.11` -> I would suggest only supporting the last 3 versions - but am also fine if we want to support `3.10`. `3.9` is quite old now though and can probably be dropped

### Is your feature related to a bug?

_No response_

### Suggested Soltuion

_No response_

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by trevorb1**
### Description

In this PR I update dependencies to be compatible with newer versions of python 

### Issue Ticket Number

Closes #212 

### Documentation

na

### CODE REVIEW

**Comment by trevorb1** [comment]
This is currently non-functional. There seems to be a `snakemake`/`pulp`/`plac` issue with some of our other packages, restricting versions to be `python<=3.11`

**Comment by trevorb1** [comment]
Okay, I have seperated the workflow and `osemosys_global` package dependencies. The package can be installed up to and including python `3.12`. The workflow can install `3.12`, but is locked to `3.11`. If the workflow install `3.12`, snakemake will produce the following error:

```bash 
ModuleNotFoundError in file /home/trevor/repos/osemosys_global/workflow/snakefile, line 8:
No module named 'asyncore'
  File "/home/trevor/miniforge3/envs/osemosys-global/lib/python3.12/site-packages/yte/__init__.py", line 3, in <module>
  File "/home/trevor/miniforge3/envs/osemosys-global/lib/python3.12/site-packages/plac.py", line 29, in <module>
  File "/home/trevor/miniforge3/envs/osemosys-global/lib/python3.12/site-packages/plac_ext.py", line 806, in <module>
``` 

As described [here](https://github.com/snakemake/snakemake/issues/2841), the solution seems to be to overwrite the `plac` install with (in the `env.yaml` file):
```bash
- pip
  - plac>=1.4
```

I am unsure how this will interface with earlier versions of python though, and will hold off on this fix right.

**Comment by trevorb1** [comment]
This PR now updates otoole to `1.1.3` and snakemake to `8.0` and package dependencies to python `3.12`. I would suggest merging (assuming this works) and address the snakemake with python `3.12` issue later. 

@maartenbrinkerink are you able to test the install to make sure everything works fine on your side, please!

**Comment by maartenbrinkerink** [comment]
Clean install and model run with updated dependencies/env file worked for me!

**Pull request merged**
